# Generated by Django 2.0.5 on 2020-04-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('category_id', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('deleted_time', models.DateTimeField()),
            ],
        ),
    ]
