# Generated by Django 2.0.5 on 2020-04-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('deleted_time', models.DateTimeField()),
            ],
        ),
    ]
